#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* Section generated by pkgbuild, do not edit */
/* .Call calls */
extern SEXP ffi_h3_version(void);
extern SEXP h3r_c_h3_to_string(void *);
extern SEXP h3r_c_point_writer_new(void *);
extern SEXP h3r_c_string_to_h3(void *);

static const R_CallMethodDef CallEntries[] = {
    {"ffi_h3_version",         (DL_FUNC) &ffi_h3_version,         0},
    {"h3r_c_h3_to_string",     (DL_FUNC) &h3r_c_h3_to_string,     1},
    {"h3r_c_point_writer_new", (DL_FUNC) &h3r_c_point_writer_new, 1},
    {"h3r_c_string_to_h3",     (DL_FUNC) &h3r_c_string_to_h3,     1},
    {NULL, NULL, 0}
};
/* End section generated by pkgbuild */

void R_init_h3r(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
